"""initial

Revision ID: c3a7ef3d9bdc
Revises: 59b7b7bedc11
Create Date: 2025-10-16 10:47:29.631712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3a7ef3d9bdc"
down_revision: Union[str, None] = "59b7b7bedc11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column("promocode", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column("promocode", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
