"""asotiation table

Revision ID: 0dc5abd3cd79
Revises: c3a7ef3d9bdc
Create Date: 2025-10-16 11:03:27.848701

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0dc5abd3cd79"
down_revision: Union[str, None] = "c3a7ef3d9bdc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
